# version está depreciado, nao é necessario mais usar.
# usar: docker compose up --build ou docker compose up --build -d
# version: '3'

services:
    web:
      tty: true # Enables debugging capabilities when attached to this container.
      stdin_open: true
      build: .
      command: bash -c 'rails s -b 0.0.0.0'
      image: cart-bomba
      restart: unless-stopped
      volumes:
        - .:/app
      ports:
        - '3000:3000'
      depends_on:
        - db
        - redis
      environment:
        RAILS_ENV: development
        DATABASE_HOST: 127.0.0.1
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
        REDIS_URL: redis://redis:6379/1
    db:
      image: postgres:16-alpine
      environment:
        DATABASE_HOST: 127.0.0.1
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
      ports:
        - '5432:5432'
      volumes:
        - postgres_data:/var/lib/postgresql/data
    redis:
        image: redis:7.0.15-alpine
        ports:
        - '6379:6379'
        volumes:
        - redis_data:/data
volumes:
    postgres_data:
    redis_data:

