default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000

local_default: &local_default
  <<: *default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", 'localhost') %>
  username: <%= ENV.fetch("DATABASE_USER", 'postgres') %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", '') %>

environment_default: &environment_default
  <<: *default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["PRODUCTION_DATABASE_HOST"] %>
  username: <%= ENV["PRODUCTION_DATABASE_USER"] %>
  password: <%= ENV["PRODUCTION_DATABASE_PASSWORD"] %>

development:
  <<: *local_default
  database: <%= ENV.fetch("DATABASE_NAME", 'cart_bomba_development') %>

test:
  <<: *local_default
  database: cart_bomba_test

production:
  <<: *environment_default
  database: <%= ENV["PRODUCTION_DATABASE_NAME"] %>
  username: <%= ENV["PRODUCTION_DATABASE_USER"] %>
  password: <%= ENV["PRODUCTION_DATABASE_PASSWORD"] %>
